### PR TITLE
update readme and link to confluence page

### PR DESCRIPTION
**Pull request by leslie-corbalt**
This PR updates the README and links to the confluence page which has more information.
The confluence page will be updated, as needed, and for each update we won't have to change the README in this repo.

### CODE REVIEW

**Review by ben-harvey — COMMENTED** [review]
You refer to the rotator variously as a 'script', 'tool', and 'app/application'; might be good to standardize on one term.

**Comment by leslie-corbalt** [comment]
> You refer to the rotator variously as a 'script', 'tool', and 'app/application'; might be good to standardize on one term.

Good point. I now reference "application" or "app", which matches the terraform name. I removed references to "tool" from the README and from the confluence page.

**Review by ben-harvey — APPROVED** [review]
LGTM!

**Comment by leslie-corbalt** [comment]
#16

**Pull request merged**
